#!/bin/sh
# The attestation: regenerate every result from scratch and check each one,
# byte for byte, against SHA256SUMS — the record the article's numbers come from.
#
#   attest.sh            regenerate, then verify. Fails on any difference.
#   attest.sh --update   regenerate, then rewrite SHA256SUMS. Review the diff first.
#
# A failure is a question, not an obstacle: either a change was meant to alter the
# results — then update, review, and revise the article if its claims moved — or it
# was not, and it is a bug. `git diff validation/oracle` shows what changed.
#
# Needs the Apple `container` CLI, like everything else in this repository.
# Needs no Node and no npm install on the host.
set -eu
cd "$(dirname "$0")"

./run.sh

# Everything run.sh writes, and nothing else: the inputs are under version control.
generated() {
  ls table3-trace.bas table3-trace-defdbl.bas table3-trace-double.bas table3-trace-bits.bas \
    table3-screen.bas runs/* screens/* comparisons.md comparisons.json replay.md replay.json \
    screens.md screens.json macroec.md macroec.json oracle.tex | LC_ALL=C sort
}
if command -v sha256sum >/dev/null; then sha() { sha256sum "$@"; }; else sha() { shasum -a 256 "$@"; }; fi

if [ "${1:-}" = "--update" ]; then
  sha $(generated) > SHA256SUMS
  echo "SHA256SUMS rewritten: $(wc -l < SHA256SUMS | tr -d ' ') files. Review the diff before committing."
  exit 0
fi

listed=$(cut -c67- SHA256SUMS | LC_ALL=C sort)
if [ "$listed" != "$(generated)" ]; then
  echo "ATTESTATION FAILED: the files generated are not the files SHA256SUMS lists." >&2
  exit 1
fi
if sha -c --quiet SHA256SUMS; then
  echo "ATTESTED: all $(wc -l < SHA256SUMS | tr -d ' ') results regenerated byte for byte."
else
  echo "ATTESTATION FAILED: the files above differ from the record. See git diff validation/oracle." >&2
  exit 1
fi
