/**
 * Where does IEEE single part from PC-BASIC's Microsoft Binary Format?
 *
 * The whole-run comparison cannot say: one step's difference is carried into every
 * later step. So this replays one step at a time. For each step k it starts from
 * PC-BASIC's own state after step k − 1, exactly, as the MKS$ bytes give it; runs
 * lines 200–290 once in our interpreter with Math.fround on every operation (R4b);
 * and compares every quantity the step computes with PC-BASIC's bytes for step k.
 * A difference here was made in that step, by that statement.
 *
 * Writes `replay.md`. Usage: node spikes/oracle-precision/replay.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BITS, readBits, ulps } from './mbf.ts';
import { loadInterpreter } from './single-precision.ts';

const here = dirname(fileURLToPath(import.meta.url));

/** In the order the step computes them, with the line that does it. */
const ORDER: [(typeof BITS)[number], string][] = [
  ['R', '200'],
  ['DD', '210'],
  ['DN', '220'],
  ['DA', '230'],
  ['DM', '240'],
  ['A', '250, 255'],
  ['N', '260'],
  ['M', '270, 275'],
  ['D', '280'],
  ['IV', '285'],
  ['T', '290'],
];
const STATE = ['T', 'D', 'IV', 'N', 'A', 'M'] as const;

const listing = readFileSync(join(here, 'table3-trace.bas'), 'utf8').split('\n').filter((l) => l.trim());
const num = (l: string): number => parseInt(l, 10);
const constants = listing.filter((l) => num(l) < 150);
const step = listing.filter((l) => num(l) >= 200 && num(l) <= 290);

/** Nine significant digits bring a single back exactly; R4b rounds the literal to single. */
function literal(v: number): string {
  const s = v.toPrecision(9);
  if (Math.fround(Number(s)) !== v) throw new Error(`${v} does not survive as ${s}`);
  return s;
}

const { Basic } = await loadInterpreter('r4b');
const { rows } = readBits(join(here, 'runs', 'r2-bits.txt'));

const differing = Object.fromEntries(ORDER.map(([q]) => [q, 0]));
const maxUlps = Object.fromEntries(ORDER.map(([q]) => [q, 0]));
const firstIn = Object.fromEntries(ORDER.map(([q]) => [q, 0]));
let stepsDiffering = 0;
const examples: string[] = [];

for (let k = 1; k < rows.length; k++) {
  const before = rows[k - 1];
  const after = rows[k];
  const interp = new Basic({ print: (text) => { throw new Error(`step ${k + 1} printed: ${text}`); } });
  interp.load(
    [
      ...constants,
      `190 ${STATE.map((v) => `${v} = ${literal(before[v])}`).join(': ')}`,
      ...step,
      '295 END',
    ].join('\n'),
  );
  await interp.run();

  const ours = (q: string): number => Number(interp.vars[q] ?? 0);
  const off = ORDER.filter(([q]) => ours(q) !== after[q]);
  for (const [q] of off) {
    differing[q]++;
    maxUlps[q] = Math.max(maxUlps[q], ulps(ours(q), after[q]));
  }
  if (off.length) {
    stepsDiffering++;
    const [q, line] = off[0];
    firstIn[q]++;
    if (examples.length < 8) {
      examples.push(
        `| ${k + 1} | ${q} (line ${line}) | ${after[q]} | ${ours(q)} | ${ulps(ours(q), after[q])} |`,
      );
    }
  }
}

const n = rows.length - 1;
const report = [
  '# One step at a time',
  '',
  'Generated by `replay.ts` from `runs/r2-bits.txt`. Do not edit by hand.',
  '',
  `Each of steps 2–${rows.length} replayed from PC-BASIC's exact state after the step before, ` +
    'in our interpreter with `Math.fround` on every operation (R4b).',
  '',
  `- **Steps whose result differs from PC-BASIC's in any quantity**: ${stepsDiffering} of ${n}.`,
  '',
  '| Quantity | Line | Steps differing | Max ulps | Steps where it is the first to differ |',
  '| --- | --- | --- | --- | --- |',
  ...ORDER.map(([q, line]) => `| ${q} | ${line} | ${differing[q]} | ${maxUlps[q]} | ${firstIn[q]} |`),
  '',
  'The first differing steps:',
  '',
  '| Step | First to differ | PC-BASIC | Ours (R4b) | ulps |',
  '| --- | --- | --- | --- | --- |',
  ...examples,
  '',
].join('\n');

writeFileSync(join(here, 'replay.md'), report);
console.log(report);
