/**
 * The program library, as the browser sees it.
 *
 * Fetched rather than bundled. The listings are the archive, not application
 * code: they live in `programs/` at the repository root so that someone
 * checking a model against its source finds them without reading any
 * TypeScript, and they are published as real files so a citation can link to
 * one. Compiling them into the JS bundle would hide both.
 *
 * One request for the whole catalog, sources inline. There are a few dozen
 * small text files and no reason to pay a round trip each.
 *
 * The index is generated by vite-plugin-programs.js, which validates every
 * sidecar at build time — so anything that arrives here has already been
 * checked, and a missing field is a failed build rather than a blank panel.
 */

import type { CatalogRun } from './program-archive.ts';
import type { ProgramDiagram, ProgramMeta, ProgramSource } from './program-catalog.ts';
import type { ProgramCrop } from './work-catalog.ts';

export interface Program extends ProgramMeta {
  /** Path within programs/: "two-tank.bas", or "<work>/<model>/model.bas". */
  file: string;
  /** The listing itself. */
  listing: string;
  /** The metadata's path within programs/. */
  sidecar: string;
  /** The published work a model belongs to; null for a single program. */
  work: { id: string; file: string } | null;
  /** The listing as printed, cropped from the page. Works only. */
  programImage: (ProgramCrop & { file: string }) | null;
  /** The published figures, each drawn by one run of the listing. */
  runs: CatalogRun[];
}

interface Catalog {
  generated: string;
  programs: (Omit<Program, 'source' | 'diagram'> & {
    source: ProgramSource | null;
    diagram: ProgramDiagram | null;
  })[];
}

let cache: Program[] | null = null;

export async function loadPrograms(): Promise<Program[]> {
  if (cache) return cache;

  const response = await fetch(`${import.meta.env.BASE_URL}programs/index.json`);
  if (!response.ok) {
    throw new Error(`Could not load the program library (HTTP ${response.status})`);
  }
  const catalog = (await response.json()) as Catalog;

  // `source` is null rather than absent in the JSON, because JSON.stringify
  // drops undefined keys and a missing key is indistinguishable from a bug.
  cache = catalog.programs.map((p) => ({
    ...p,
    source: p.source ?? undefined,
    diagram: p.diagram ?? undefined,
  }));
  return cache;
}

export function findProgram(programs: Program[], id: string | undefined): Program | undefined {
  if (!id) return undefined;
  return programs.find((p) => p.id === id);
}

/** The published URL of a listing, for the citation to link to. */
export function programUrl(program: Program): string {
  return `${import.meta.env.BASE_URL}programs/${program.file}`;
}

/** The published URL of a program's diagram, if it has one. */
export function diagramUrl(program: Program): string | null {
  return program.diagram ? `${import.meta.env.BASE_URL}programs/${program.diagram.file}` : null;
}
