/**
 * The program library, as the browser sees it.
 *
 * Fetched rather than bundled. The listings are the archive, not application
 * code: they live in `programs/` at the repository root so that someone
 * checking a model against its source finds them without reading any
 * TypeScript, and they are published as real files so a citation can link to
 * one. Compiling them into the JS bundle would hide both.
 *
 * One request for the whole catalog, sources inline. There are a few dozen
 * small text files and no reason to pay a round trip each.
 *
 * The index is generated by vite-plugin-programs.js, which validates every
 * sidecar at build time — so anything that arrives here has already been
 * checked, and a missing field is a failed build rather than a blank panel.
 */

import type { ProgramMeta, ProgramSource } from './program-catalog.ts';

export interface Program extends ProgramMeta {
  /** Filename within programs/, e.g. "two-tank.bas". */
  file: string;
  /** The listing itself. */
  listing: string;
}

interface Catalog {
  generated: string;
  programs: (Omit<Program, 'source'> & { source: ProgramSource | null })[];
}

let cache: Program[] | null = null;

export async function loadPrograms(): Promise<Program[]> {
  if (cache) return cache;

  const response = await fetch(`${import.meta.env.BASE_URL}programs/index.json`);
  if (!response.ok) {
    throw new Error(`Could not load the program library (HTTP ${response.status})`);
  }
  const catalog = (await response.json()) as Catalog;

  // `source` is null rather than absent in the JSON, because JSON.stringify
  // drops undefined keys and a missing key is indistinguishable from a bug.
  cache = catalog.programs.map((p) => ({ ...p, source: p.source ?? undefined }));
  return cache;
}

export function findProgram(programs: Program[], id: string | undefined): Program | undefined {
  if (!id) return undefined;
  return programs.find((p) => p.id === id);
}

/** The published URL of a listing, for the citation to link to. */
export function programUrl(program: Program): string {
  return `${import.meta.env.BASE_URL}programs/${program.file}`;
}
